/**
 * All user-facing copy lives here — pages and islands must not carry naked
 * string literals. When localization lands, this module becomes a per-locale
 * lookup and nothing else changes. Compose, don't concatenate, at call sites.
 */

export const APP_NAME = "specpasa";

/** "Part — Part — specpasa" browser/page titles. */
export const pageTitle = (...parts: string[]): string => [...parts, APP_NAME].join(" — ");

export const t = {
  ui: {
    close: "Close",
    closeGlyph: "✕",
  },
  nav: {
    projects: "Projects",
    providers: "AI Providers",
    members: "Members",
    logout: "Log out",
    theme: {
      system: "Theme: match system",
      light: "Theme: light",
      dark: "Theme: dark",
      glyphSystem: "◐",
      glyphLight: "☀",
      glyphDark: "☾",
    },
  },
  auth: {
    setupHeading: `Welcome to ${APP_NAME}`,
    setupTagline: "First run: create the admin account and your workspace.",
    setupTitle: pageTitle("Set up"),
    name: "Your name",
    email: "Email",
    password: "Password (8+ characters)",
    passwordPlain: "Password",
    workspaceName: "Workspace name",
    workspacePlaceholder: "e.g. worldofpasa",
    createWorkspace: "Create workspace",
    loginHeading: "Log in",
    loginTitle: pageTitle("Log in"),
    loginSubmit: "Log in",
  },
  projects: {
    listLabel: "Projects",
    empty: "No projects yet — create the first one below.",
    newHeading: "New project",
    namePlaceholder: "Project name",
    descriptionPlaceholder: "Description (optional)",
    create: "Create project",
  },
  intents: {
    listLabel: "Intents",
    empty: "No intents yet. An intent captures one goal — e.g. “Self-serve onboarding”.",
    newHeading: "New intent",
    titlePlaceholder: "Intent title",
    descriptionPlaceholder: "Description (optional)",
    create: "Create intent",
  },
  specs: {
    listLabel: "Specs",
    empty: "No specs yet — start with a blank PRD below.",
    newHeading: "New spec (starts in the PRD phase)",
    titlePlaceholder: "Spec title",
    create: "Create spec",
    versionHistory: "Version history",
  },
  editor: {
    blankSpec: "Blank spec",
    version: (n: number) => `Version ${n}`,
    unsaved: "unsaved changes",
    draftSaved: "Draft saved",
    draftRestored: "Restored your unsaved draft — it isn't a version yet.",
    discardDraft: "Discard draft",
    edit: "Edit",
    preview: "Preview",
    save: "Save as new version",
    saving: "Saving…",
    placeholder:
      "Start with rough thoughts, bullet points, links — anything.\nThen ask AI to draft the PRD below.",
    aiHeading: "Brainstorm with AI",
    aiNoProviders: "No AI providers configured yet — ",
    aiNoProvidersLink: "add one in settings",
    aiPromptDraft: "Rough thoughts to turn into a draft PRD…",
    aiPromptRevise: "How should the AI revise the current document?",
    aiDraft: "Draft with AI",
    aiRevise: "Revise with AI",
    aiGenerating: "Generating…",
    aiAutoSaveNote: "Saves automatically as a new version marked AI-generated.",
    aiIncludesComments: (n: number) =>
      n === 1
        ? "1 open review comment will be included"
        : `${n} open review comments will be included`,
    aiContextLabel: "Context",
    aiRefIncluded: "Included — click to exclude",
    aiRefExcluded: "Excluded — click to include",
  },
  versions: {
    heading: "Version history",
    crumb: "versions",
    titleFor: (spec: string) => pageTitle("Versions", spec),
    empty: "No versions yet.",
    aiBadge: "AI-generated",
    diffSummary: (base: string, added: number, removed: number, unchanged: number) =>
      `Block-level diff against ${base} — ${added} added, ${removed} removed, ${unchanged} unchanged.`,
    blankBase: "the blank spec",
    versionBase: (n: number) => `v${n}`,
    backToWorkspace: "Back to workspace",
    addedBadge: "Added",
    removedBadge: "Removed",
  },
  providers: {
    heading: "AI Providers",
    tagline:
      "Workspace-scoped provider configs. API keys are encrypted at rest and never sent to the browser.",
    title: pageTitle("AI Providers"),
    detectedHeading: "Detected on this host",
    detectedItem: (name: string, detail: string) => `✓ ${name} — ${detail}`,
    nothingDetected:
      "No local AI backends detected — looked for Ollama on localhost:11434 and the claude/codex CLIs on PATH.",
    empty: "No providers configured yet.",
    keyStored: "key stored (encrypted)",
    remove: "Remove",
    addAnthropic: "Add Anthropic",
    addOllama: "Add Ollama (local)",
    displayNameAnthropic: "Display name (e.g. Claude)",
    displayNameOllama: "Display name (e.g. Local Llama)",
    apiKeyPlaceholder: "API key (sk-ant-…)",
    modelPlaceholder: "Model (e.g. llama3.2)",
    baseUrlPlaceholder: "Base URL (default http://localhost:11434)",
    addLocalCli: "Add local CLI",
    localCliNote: "Runs the CLI on this host — nothing leaves the machine, no API key needed.",
    displayNameLocalCli: "Display name (e.g. Claude CLI)",
    cliCommandLabel: "Command",
    add: "Add",
  },
  lifecycle: {
    heading: "Lifecycle",
    requestReview: "Request review",
    backToDraft: "Back to draft",
    freeze: "Freeze",
    frozenNote: (when: string) => `Frozen ${when} — this spec is immutable. Fork it to iterate.`,
    freezeNeedsVersion: "Save at least one version before freezing.",
    startNextPhase: (phase: string) => `Start ${phase.toUpperCase()} phase`,
    derivedFrom: (phase: string) => `Derived from the frozen ${phase.toUpperCase()} spec`,
    seedHeading: (title: string, phase: string) => `# ${title} — ${phase.toUpperCase()}`,
    seedNote: (phase: string, n: number) =>
      `> Derived from the frozen ${phase.toUpperCase()} (v${n}). The source document is attached as a reference and fed to AI drafts.`,
    fork: "Fork",
    forkTitle: (title: string) => `${title} (fork)`,
    statusLabel: "Status",
    statusName: (status: string) =>
      (({ draft: "Draft", in_review: "In review", frozen: "Frozen" }) as Record<string, string>)[
        status
      ] ?? status,
    openThreadsWarning: (n: number) =>
      n === 1 ? "1 comment thread is still open." : `${n} comment threads are still open.`,
    /** Client-side template for the live count (SpecLifecycle inline script). */
    openThreadsWarningTemplate: "{n} comment threads are still open.",
    freezeConfirmLabel: "Freeze anyway",
  },
  references: {
    heading: "References",
    tagline: "Attached links, code, and specs are fed to AI drafts as context.",
    empty: "No references attached.",
    add: "Add reference",
    kindLabel: "Kind",
    kindUrl: "URL",
    kindGithub: "GitHub file",
    kindSpec: "Spec",
    kindFile: "File upload",
    kindShort: (kind: string) =>
      (({ url: "URL", github_code: "GH", spec: "SPEC", file: "FILE" }) as Record<string, string>)[
        kind
      ] ?? kind,
    titlePlaceholder: "Title",
    urlPlaceholder: "https://…",
    githubPlaceholder: "https://github.com/owner/repo/blob/main/path/to/file.ts",
    specIdPlaceholder: "Spec ID (from the spec URL)",
    fileLabel: "File (up to 10 MB)",
    remove: "Remove",
    addButton: "+ Add",
    previewTitle: "Reference preview",
    previewUnsupported: "No inline preview for this file type — download it instead.",
    previewLoading: "Loading preview…",
    download: "Download",
  },
  workspace: {
    titleBlock: {
      spec: "Spec",
      project: "Project",
      phase: "Phase",
      rev: "Rev",
    },
    outline: "Outline",
    outlineEmpty: "Headings will appear here as the document grows.",
    collapsePanel: "Collapse panel",
    expandPanel: "Expand panel",
    attachments: "Attachments",
    reading: "Reading",
    editing: "Edit",
    commentStub: "Commenting unavailable",
    commentsHeading: "Comments",
    commentsEmpty: "No comments yet — hover a block and press + to start a thread.",
    commentsResolved: "Resolved",
    aiPill: "✦ Ask AI",
    aiCollapse: "Hide",
    emptySheet: "This spec is blank — switch to Edit or ask AI to draft it.",
    commentAdd: "Comment on this block",
  },
  members: {
    heading: "Members",
    title: pageTitle("Members"),
    tagline: "Everyone in this workspace, and pending invites.",
    inviteHeading: "Invite a member",
    emailPlaceholder: "colleague@example.com",
    roleLabel: "Role",
    invite: "Send invite",
    pendingHeading: "Pending invites",
    inviteLinkLabel: "Invite link",
    noPending: "No pending invites.",
    expired: "expired",
  },
  invite: {
    heading: (workspace: string) => `Join ${workspace} on ${APP_NAME}`,
    tagline: "Set up your account to accept the invite.",
    title: pageTitle("Join"),
    role: (role: string) => `You are joining as ${role}.`,
    accept: "Join workspace",
    invalid: "This invite link is invalid, expired, or already used.",
  },
  comments: {
    heading: "Review",
    summary: (open: number, resolved: number) => `${open} open · ${resolved} resolved`,
    commentOn: "Comment",
    post: "Post",
    reply: "Reply",
    resolve: "Resolve",
    reopen: "Reopen",
    resolved: "Resolved",
    open: "Open",
    placeholder: "Write a comment…",
    replyPlaceholder: "Write a reply…",
    empty: "No comments yet — select a block below to start a thread.",
    noBlocks: "Save a first version to start reviewing.",
    threadCount: (n: number) => (n === 1 ? "1 thread" : `${n} threads`),
    composerHeading: "New comment",
    cancel: "Cancel",
    selectHint: "Hover a block in the document and click + to start a thread.",
  },
  connectors: {
    heading: "Connectors",
    on: "On",
    connect: "Connect",
    soon: "Soon",
    github: "GitHub",
    githubDetail: "Docs & issues export",
    drive: "Google Drive",
    driveDetail: "Reference sync",
    confluence: "Confluence",
    confluenceDetail: "Spec sync",
    jira: "Jira",
    jiraDetail: "Task export",
  },
  integrations: {
    heading: "Integrations",
    tagline:
      "Connect this project to the tools your team ships with. Tokens are encrypted at rest.",
    githubHeading: "GitHub",
    connected: (repo: string) => `Connected to ${repo}`,
    ownerPlaceholder: "Owner (e.g. worldofpasa)",
    repoPlaceholder: "Repository (e.g. product-specs)",
    branchPlaceholder: "Branch (default branch if empty)",
    basePathPlaceholder: "Folder for exported specs (default: specs)",
    tokenPlaceholder: "Personal access token (repo scope)",
    tokenStored: "token stored (encrypted)",
    connect: "Connect GitHub",
    disconnect: "Disconnect",
    none: "No integrations connected yet.",
  },
  export: {
    title: (spec: string) => pageTitle("Export", spec),
    crumb: "export",
    heading: "Export",
    needsIntegration: "Connect a GitHub integration on the project page first.",
    needsFrozen: "Freeze this spec to enable exporting — exports always ship a pinned version.",
    docHeading: "Spec document → GitHub",
    docExplainer: (repo: string) =>
      `Commits the frozen document as markdown to ${repo} (updated in place on re-export).`,
    docButton: "Export document",
    tasksHeading: "Epics & tasks → GitHub Issues",
    tasksExplainer:
      "Structure the tasks document into epics first, review the grouping, then create one issue per epic (updated in place on re-export).",
    structureButton: "Structure into epics",
    restructureButton: "Re-structure from document",
    tasksButton: "Create GitHub issues",
    tasksOnly: "Task export is available for TASKS-phase specs.",
    epicsEmpty: "No epics yet — structure the document to preview the grouping.",
    epicTaskCount: (n: number) => (n === 1 ? "1 task" : `${n} tasks`),
    removeEpic: "Remove",
    exportedHeading: "Export records",
    exportedEmpty: "Nothing exported yet.",
    exportedDoc: "Document",
    exportedIssue: "Issue",
    reExportNote: "Re-exporting updates the same file and issues — no duplicates.",
    restructuredNotice: (n: number) =>
      `${n === 1 ? "1 issue was" : `${n} issues were`} previously exported from the old structure. Re-exporting creates fresh issues; the old GitHub issues remain and may need manual closing.`,
    lastExported: (when: string) => `last exported ${when}`,
  },
  presence: {
    viewing: (name: string) => `${name} is viewing`,
    label: "Currently viewing",
    more: (n: number) => `+${n}`,
  },
} as const;
